// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using PDV.Infra.Context;
using PDV.Infra.Setup;

namespace PDV.Infra.Migrations
{
    [DbContext(typeof(PdvContext))]
    partial class PdvContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PDV.Dominio.ValorMonetario.Valor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DescricaoValor")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasMaxLength(8);

                    b.Property<int>("TipoValor");

                    b.Property<decimal>("ValorMonetario");

                    b.HasKey("Id");

                    b.ToTable("Valores");
                });

            modelBuilder.Entity("PDV.Dominio.Venda.Troco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdValor");

                    b.Property<Guid>("IdVenda");

                    b.Property<int>("QuantidadeValor");

                    b.HasKey("Id");

                    b.HasIndex("IdValor");

                    b.HasIndex("IdVenda");

                    b.ToTable("Trocos");
                });

            modelBuilder.Entity("PDV.Dominio.Venda.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("ValorRecebido");

                    b.Property<decimal>("ValorTotal");

                    b.HasKey("Id");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("PDV.Dominio.Venda.Troco", b =>
                {
                    b.HasOne("PDV.Dominio.ValorMonetario.Valor", "Valor")
                        .WithMany("Troco")
                        .HasForeignKey("IdValor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PDV.Dominio.Venda.Venda", "Venda")
                        .WithMany("Trocos")
                        .HasForeignKey("IdVenda")
                        .OnDelete(DeleteBehavior.Cascade);
                });            
#pragma warning restore 612, 618
        }
    }
}
