// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PDV.Infra.Context;

namespace PDV.Infra.Migrations
{
    [DbContext(typeof(PdvContext))]
    partial class PdvContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PDV.Dominio.ValorMonetario.Valor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DescricaoValor")
                        .IsRequired()
                        .HasColumnType("varchar(8)")
                        .HasMaxLength(8);

                    b.Property<int>("TipoValor");

                    b.Property<decimal>("ValorMonetario");

                    b.HasKey("Id");

                    b.ToTable("Valores");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3ec29908-ac3d-4355-b2b8-fca39af8a1d4"),
                            DescricaoValor = "R$100,00",
                            TipoValor = 1,
                            ValorMonetario = 100m
                        },
                        new
                        {
                            Id = new Guid("bfdcfe55-ced4-44c8-8f81-3f662ee403b2"),
                            DescricaoValor = "R$50,00",
                            TipoValor = 1,
                            ValorMonetario = 50m
                        },
                        new
                        {
                            Id = new Guid("83c50805-a8c4-470b-af8a-5afb2eb6e955"),
                            DescricaoValor = "R$20,00",
                            TipoValor = 1,
                            ValorMonetario = 20m
                        },
                        new
                        {
                            Id = new Guid("ba2bd123-70c3-4bb1-a5f6-f4f25437b47a"),
                            DescricaoValor = "R$10,00",
                            TipoValor = 1,
                            ValorMonetario = 10m
                        },
                        new
                        {
                            Id = new Guid("1ef801ee-b2e0-489c-82b3-78a48ef266d3"),
                            DescricaoValor = "R$0,50",
                            TipoValor = 0,
                            ValorMonetario = 0.5m
                        },
                        new
                        {
                            Id = new Guid("bac10056-b884-4d95-aa68-e6797794c6d2"),
                            DescricaoValor = "R$0,10",
                            TipoValor = 0,
                            ValorMonetario = 0.1m
                        },
                        new
                        {
                            Id = new Guid("8894a636-4ba3-4476-8224-a1da4a69a4e8"),
                            DescricaoValor = "R$0,05",
                            TipoValor = 0,
                            ValorMonetario = 0.05m
                        },
                        new
                        {
                            Id = new Guid("aa9d62aa-9fe4-4a45-b223-7da7447ed377"),
                            DescricaoValor = "R$0,01",
                            TipoValor = 0,
                            ValorMonetario = 0.01m
                        });
                });

            modelBuilder.Entity("PDV.Dominio.Venda.Troco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("IdValor");

                    b.Property<Guid>("IdVenda");

                    b.Property<int>("QuantidadeValor");

                    b.HasKey("Id");

                    b.HasIndex("IdValor");

                    b.HasIndex("IdVenda");

                    b.ToTable("Trocos");
                });

            modelBuilder.Entity("PDV.Dominio.Venda.Venda", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("ValorRecebido");

                    b.Property<decimal>("ValorTotal");

                    b.HasKey("Id");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("PDV.Dominio.Venda.Troco", b =>
                {
                    b.HasOne("PDV.Dominio.ValorMonetario.Valor", "Valor")
                        .WithMany("Troco")
                        .HasForeignKey("IdValor")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PDV.Dominio.Venda.Venda", "Venda")
                        .WithMany("Trocos")
                        .HasForeignKey("IdVenda")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
